name: 'Package xbwd'
description: "Create packages of xchain witness server"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build packages
      shell: bash
      run: ./Builds/CMake/packaging/build_packages.sh

    - name: Upload packages
      uses: actions/upload-artifact@v3
      with:
        name: xbwd_packages
        path: packages
